name: Daily Robot Parser

on:
  schedule:
    # Запуск каждый день в 03:00 UTC (07:00 по Саратову, GMT+4)
    - cron: '0 3 * * *'

  # Можно также запускать вручную
  workflow_dispatch:

jobs:
  parse-robots:
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Run Rube Recipe - Parse Robots
        run: |
          echo "Starting robot parser..."

          # Вызываем Rube Recipe API
          curl -X POST "https://backend.composio.dev/api/v1/actions/rcp_zqcpF4RK7QIv/execute" \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.COMPOSIO_API_KEY }}" \
            -d '{
              "input": {
                "api_key": "${{ secrets.ROBOTS_API_KEY }}",
                "api_url": "https://robototehnika.vercel.app/api/robots",
                "search_mode": "all"
              }
            }' \
            | jq '.'

          echo "✅ Robot parser completed!"

      - name: 📊 Show Summary
        run: |
          echo "🎉 Daily robot parsing workflow completed!"
          echo "Check your database at https://robototehnika.vercel.app/api/robots"
